# Generated by Django 4.0.6 on 2022-07-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoLists',
            new_name='TodoList',
        ),
    ]
