# Generated by Django 4.0.6 on 2022-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0003_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heading',
        ),
    ]
